name: Run build

on:
  pull_request:
    types: [ opened, synchronize, reopened, edited ]
    branches:
      - master
      - release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Build Project
        run: ./gradlew assemble

      - name: Save apk
        uses: actions/upload-artifact@v2
        with:
          name: android-artifact
          path: |
            **/*.apk
          retention-days: 7