name: detekt

on:
  pull_request:
    types: [ opened, synchronize, reopened, edited ]
    branches:
      - master
      - release

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: "detekt"
        run: ./gradlew detekt --continue